---
version: "3"
services:

  server:
    image: server_container
    build:
      context: ../../
      args:
        BASE_IMAGE: python:3.6
    ports:
      - 8000:8000
    working_dir: /opt/app
    volumes:
      - ./:/opt/app/
    command: python3 main.py
